vim.g.loaded_python_provier = 0
vim.g.loaded_python3_provider = 0
vim.g.python_host_skip_check = 1
vim.g.python_host_prog='/bin/python2'
vim.g.python3_host_skip_check = 1
vim.g.python3_host_prog='/bin/python3'
vim.opt.pyxversion=3
vim.g.EditorConfig_core_mode = 'external_command'
vim.g.matchparen_timeout = 20
vim.g.matchparen_insert_timeout = 20
